/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppWorkRouteImport } from './routes/app.work'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppAdminMembersRouteImport } from './routes/app.admin.members'
import { Route as AppMailFolderRouteImport } from './routes/app.mail.$folder'
import { Route as AppMailFolderIndexRouteImport } from './routes/app.mail.$folder.index'
import { Route as AppMailFolderThreadIdRouteImport } from './routes/app.mail.$folder.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppMailFolderRoute = AppMailFolderRouteImport.update({
  id: '/mail/$folder',
  path: '/mail/$folder',
  getParentRoute: () => AppRoute,
} as any)
const AppMailFolderIndexRoute = AppMailFolderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMailFolderRoute,
} as any)
const AppMailFolderThreadIdRoute = AppMailFolderThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppMailFolderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/people': typeof AppPeopleRoute
  '/app/search': typeof AppSearchRoute
  '/app/work': typeof AppWorkRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/mail/$folder': typeof AppMailFolderRouteWithChildren
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/mail/$folder/$threadId': typeof AppMailFolderThreadIdRoute
  '/app/mail/$folder/': typeof AppMailFolderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/people': typeof AppPeopleRoute
  '/app/search': typeof AppSearchRoute
  '/app/work': typeof AppWorkRoute
  '/app': typeof AppIndexRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/mail/$folder/$threadId': typeof AppMailFolderThreadIdRoute
  '/app/mail/$folder': typeof AppMailFolderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/people': typeof AppPeopleRoute
  '/app/search': typeof AppSearchRoute
  '/app/work': typeof AppWorkRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/mail/$folder': typeof AppMailFolderRouteWithChildren
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/mail/$folder/$threadId': typeof AppMailFolderThreadIdRoute
  '/app/mail/$folder/': typeof AppMailFolderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/app'
    | '/app/admin'
    | '/app/calendar'
    | '/app/people'
    | '/app/search'
    | '/app/work'
    | '/app/'
    | '/app/admin/members'
    | '/app/mail/$folder'
    | '/app/admin/'
    | '/app/mail/$folder/$threadId'
    | '/app/mail/$folder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/app/calendar'
    | '/app/people'
    | '/app/search'
    | '/app/work'
    | '/app'
    | '/app/admin/members'
    | '/app/admin'
    | '/app/mail/$folder/$threadId'
    | '/app/mail/$folder'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/app'
    | '/app/admin'
    | '/app/calendar'
    | '/app/people'
    | '/app/search'
    | '/app/work'
    | '/app/'
    | '/app/admin/members'
    | '/app/mail/$folder'
    | '/app/admin/'
    | '/app/mail/$folder/$threadId'
    | '/app/mail/$folder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/work': {
      id: '/app/work'
      path: '/work'
      fullPath: '/app/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/members': {
      id: '/app/admin/members'
      path: '/members'
      fullPath: '/app/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/mail/$folder': {
      id: '/app/mail/$folder'
      path: '/mail/$folder'
      fullPath: '/app/mail/$folder'
      preLoaderRoute: typeof AppMailFolderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mail/$folder/': {
      id: '/app/mail/$folder/'
      path: '/'
      fullPath: '/app/mail/$folder/'
      preLoaderRoute: typeof AppMailFolderIndexRouteImport
      parentRoute: typeof AppMailFolderRoute
    }
    '/app/mail/$folder/$threadId': {
      id: '/app/mail/$folder/$threadId'
      path: '/$threadId'
      fullPath: '/app/mail/$folder/$threadId'
      preLoaderRoute: typeof AppMailFolderThreadIdRouteImport
      parentRoute: typeof AppMailFolderRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppMailFolderRouteChildren {
  AppMailFolderThreadIdRoute: typeof AppMailFolderThreadIdRoute
  AppMailFolderIndexRoute: typeof AppMailFolderIndexRoute
}

const AppMailFolderRouteChildren: AppMailFolderRouteChildren = {
  AppMailFolderThreadIdRoute: AppMailFolderThreadIdRoute,
  AppMailFolderIndexRoute: AppMailFolderIndexRoute,
}

const AppMailFolderRouteWithChildren = AppMailFolderRoute._addFileChildren(
  AppMailFolderRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppSearchRoute: typeof AppSearchRoute
  AppWorkRoute: typeof AppWorkRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMailFolderRoute: typeof AppMailFolderRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppSearchRoute: AppSearchRoute,
  AppWorkRoute: AppWorkRoute,
  AppIndexRoute: AppIndexRoute,
  AppMailFolderRoute: AppMailFolderRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
