/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as MoveInRouteImport } from './routes/move-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OwnershipRouteImport } from './routes/ownership'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as AiAutomationRouteImport } from './routes/ai_.automation'
import { Route as AiCreditsRouteImport } from './routes/ai_.credits'
import { Route as AiKnowledgeRouteImport } from './routes/ai_.knowledge'
import { Route as AiStudioRouteImport } from './routes/ai_.studio'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAiCenterRouteImport } from './routes/app.ai-center'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppFounderRouteImport } from './routes/app.founder'
import { Route as AppOrgRouteImport } from './routes/app.org'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppWorkRouteImport } from './routes/app.work'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppAdminAddressesRouteImport } from './routes/app.admin.addresses'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppAdminExportRouteImport } from './routes/app.admin.export'
import { Route as AppAdminMembersRouteImport } from './routes/app.admin.members'
import { Route as AppAdminTeamsRouteImport } from './routes/app.admin.teams'
import { Route as AppCrmIndexRouteImport } from './routes/app.crm.index'
import { Route as AppCrmActivityRouteImport } from './routes/app.crm.activity'
import { Route as AppCrmCollabRouteImport } from './routes/app.crm.collab'
import { Route as AppCrmLeadsRouteImport } from './routes/app.crm.leads'
import { Route as AppCrmPipelineRouteImport } from './routes/app.crm.pipeline'
import { Route as AppFounderAiRouteImport } from './routes/app.founder_.ai'
import { Route as AppFounderCrmRouteImport } from './routes/app.founder_.crm'
import { Route as AppFounderOrgRouteImport } from './routes/app.founder_.org'
import { Route as AppMailFolderRouteImport } from './routes/app.mail.$folder'
import { Route as AppOrgIndexRouteImport } from './routes/app.org.index'
import { Route as AppOrgAuditRouteImport } from './routes/app.org.audit'
import { Route as AppOrgComplianceRouteImport } from './routes/app.org.compliance'
import { Route as AppOrgDepartmentsRouteImport } from './routes/app.org.departments'
import { Route as AppOrgGraphRouteImport } from './routes/app.org.graph'
import { Route as AppOrgMembersRouteImport } from './routes/app.org.members'
import { Route as AppOrgPoliciesRouteImport } from './routes/app.org.policies'
import { Route as AppOrgRolesRouteImport } from './routes/app.org.roles'
import { Route as AppOrgSecurityRouteImport } from './routes/app.org.security'
import { Route as AppFounderAiIndexRouteImport } from './routes/app.founder_.ai.index'
import { Route as AppFounderAiArenaRouteImport } from './routes/app.founder_.ai.arena'
import { Route as AppFounderAiAutomationRouteImport } from './routes/app.founder_.ai.automation'
import { Route as AppFounderAiBillingRouteImport } from './routes/app.founder_.ai.billing'
import { Route as AppFounderAiMemoryRouteImport } from './routes/app.founder_.ai.memory'
import { Route as AppFounderAiPromptsRouteImport } from './routes/app.founder_.ai.prompts'
import { Route as AppFounderAiReceiptsRouteImport } from './routes/app.founder_.ai.receipts'
import { Route as AppFounderAiStudioRouteImport } from './routes/app.founder_.ai.studio'
import { Route as AppMailFolderIndexRouteImport } from './routes/app.mail.$folder.index'
import { Route as AppMailFolderThreadIdRouteImport } from './routes/app.mail.$folder.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveInRoute = MoveInRouteImport.update({
  id: '/move-in',
  path: '/move-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnershipRoute = OwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai_/automation',
  path: '/ai/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCreditsRoute = AiCreditsRouteImport.update({
  id: '/ai_/credits',
  path: '/ai/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKnowledgeRoute = AiKnowledgeRouteImport.update({
  id: '/ai_/knowledge',
  path: '/ai/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai_/studio',
  path: '/ai/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCenterRoute = AppAiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppFounderRoute = AppFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAddressesRoute = AppAdminAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminExportRoute = AppAdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTeamsRoute = AppAdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmActivityRoute = AppCrmActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmCollabRoute = AppCrmCollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmLeadsRoute = AppCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmPipelineRoute = AppCrmPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppFounderAiRoute = AppFounderAiRouteImport.update({
  id: '/founder_/ai',
  path: '/founder/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppFounderCrmRoute = AppFounderCrmRouteImport.update({
  id: '/founder_/crm',
  path: '/founder/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppFounderOrgRoute = AppFounderOrgRouteImport.update({
  id: '/founder_/org',
  path: '/founder/org',
  getParentRoute: () => AppRoute,
} as any)
const AppMailFolderRoute = AppMailFolderRouteImport.update({
  id: '/mail/$folder',
  path: '/mail/$folder',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgAuditRoute = AppOrgAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgComplianceRoute = AppOrgComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgDepartmentsRoute = AppOrgDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgGraphRoute = AppOrgGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgMembersRoute = AppOrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgPoliciesRoute = AppOrgPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgRolesRoute = AppOrgRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSecurityRoute = AppOrgSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppFounderAiIndexRoute = AppFounderAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFounderAiRoute,
} as any)
const AppFounderAiArenaRoute = AppFounderAiArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AppFounderAiRoute,
} as any)
const AppFounderAiAutomationRoute = AppFounderAiAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppFounderAiRoute,
} as any)
const AppFounderAiBillingRoute = AppFounderAiBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppFounderAiRoute,
} as any)
const AppFounderAiMemoryRoute = AppFounderAiMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppFounderAiRoute,
} as any)
const AppFounderAiPromptsRoute = AppFounderAiPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppFounderAiRoute,
} as any)
const AppFounderAiReceiptsRoute = AppFounderAiReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppFounderAiRoute,
} as any)
const AppFounderAiStudioRoute = AppFounderAiStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppFounderAiRoute,
} as any)
const AppMailFolderIndexRoute = AppMailFolderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMailFolderRoute,
} as any)
const AppMailFolderThreadIdRoute = AppMailFolderThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppMailFolderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/move-in': typeof MoveInRoute
  '/onboarding': typeof OnboardingRoute
  '/ownership': typeof OwnershipRoute
  '/pages': typeof PagesRoute
  '/plans': typeof PlansRoute
  '/security': typeof SecurityRoute
  '/ai/automation': typeof AiAutomationRoute
  '/ai/credits': typeof AiCreditsRoute
  '/ai/knowledge': typeof AiKnowledgeRoute
  '/ai/studio': typeof AiStudioRoute
  '/app/account': typeof AppAccountRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/founder': typeof AppFounderRoute
  '/app/org': typeof AppOrgRouteWithChildren
  '/app/people': typeof AppPeopleRoute
  '/app/search': typeof AppSearchRoute
  '/app/work': typeof AppWorkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/addresses': typeof AppAdminAddressesRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/export': typeof AppAdminExportRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/teams': typeof AppAdminTeamsRoute
  '/app/crm/activity': typeof AppCrmActivityRoute
  '/app/crm/collab': typeof AppCrmCollabRoute
  '/app/crm/leads': typeof AppCrmLeadsRoute
  '/app/crm/pipeline': typeof AppCrmPipelineRoute
  '/app/founder/ai': typeof AppFounderAiRouteWithChildren
  '/app/founder/crm': typeof AppFounderCrmRoute
  '/app/founder/org': typeof AppFounderOrgRoute
  '/app/mail/$folder': typeof AppMailFolderRouteWithChildren
  '/app/org/audit': typeof AppOrgAuditRoute
  '/app/org/compliance': typeof AppOrgComplianceRoute
  '/app/org/departments': typeof AppOrgDepartmentsRoute
  '/app/org/graph': typeof AppOrgGraphRoute
  '/app/org/members': typeof AppOrgMembersRoute
  '/app/org/policies': typeof AppOrgPoliciesRoute
  '/app/org/roles': typeof AppOrgRolesRoute
  '/app/org/security': typeof AppOrgSecurityRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/org/': typeof AppOrgIndexRoute
  '/app/founder/ai/arena': typeof AppFounderAiArenaRoute
  '/app/founder/ai/automation': typeof AppFounderAiAutomationRoute
  '/app/founder/ai/billing': typeof AppFounderAiBillingRoute
  '/app/founder/ai/memory': typeof AppFounderAiMemoryRoute
  '/app/founder/ai/prompts': typeof AppFounderAiPromptsRoute
  '/app/founder/ai/receipts': typeof AppFounderAiReceiptsRoute
  '/app/founder/ai/studio': typeof AppFounderAiStudioRoute
  '/app/mail/$folder/$threadId': typeof AppMailFolderThreadIdRoute
  '/app/founder/ai/': typeof AppFounderAiIndexRoute
  '/app/mail/$folder/': typeof AppMailFolderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/move-in': typeof MoveInRoute
  '/onboarding': typeof OnboardingRoute
  '/ownership': typeof OwnershipRoute
  '/pages': typeof PagesRoute
  '/plans': typeof PlansRoute
  '/security': typeof SecurityRoute
  '/ai/automation': typeof AiAutomationRoute
  '/ai/credits': typeof AiCreditsRoute
  '/ai/knowledge': typeof AiKnowledgeRoute
  '/ai/studio': typeof AiStudioRoute
  '/app/account': typeof AppAccountRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/founder': typeof AppFounderRoute
  '/app/people': typeof AppPeopleRoute
  '/app/search': typeof AppSearchRoute
  '/app/work': typeof AppWorkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/admin/addresses': typeof AppAdminAddressesRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/export': typeof AppAdminExportRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/teams': typeof AppAdminTeamsRoute
  '/app/crm/activity': typeof AppCrmActivityRoute
  '/app/crm/collab': typeof AppCrmCollabRoute
  '/app/crm/leads': typeof AppCrmLeadsRoute
  '/app/crm/pipeline': typeof AppCrmPipelineRoute
  '/app/founder/crm': typeof AppFounderCrmRoute
  '/app/founder/org': typeof AppFounderOrgRoute
  '/app/org/audit': typeof AppOrgAuditRoute
  '/app/org/compliance': typeof AppOrgComplianceRoute
  '/app/org/departments': typeof AppOrgDepartmentsRoute
  '/app/org/graph': typeof AppOrgGraphRoute
  '/app/org/members': typeof AppOrgMembersRoute
  '/app/org/policies': typeof AppOrgPoliciesRoute
  '/app/org/roles': typeof AppOrgRolesRoute
  '/app/org/security': typeof AppOrgSecurityRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/crm': typeof AppCrmIndexRoute
  '/app/org': typeof AppOrgIndexRoute
  '/app/founder/ai/arena': typeof AppFounderAiArenaRoute
  '/app/founder/ai/automation': typeof AppFounderAiAutomationRoute
  '/app/founder/ai/billing': typeof AppFounderAiBillingRoute
  '/app/founder/ai/memory': typeof AppFounderAiMemoryRoute
  '/app/founder/ai/prompts': typeof AppFounderAiPromptsRoute
  '/app/founder/ai/receipts': typeof AppFounderAiReceiptsRoute
  '/app/founder/ai/studio': typeof AppFounderAiStudioRoute
  '/app/mail/$folder/$threadId': typeof AppMailFolderThreadIdRoute
  '/app/founder/ai': typeof AppFounderAiIndexRoute
  '/app/mail/$folder': typeof AppMailFolderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/move-in': typeof MoveInRoute
  '/onboarding': typeof OnboardingRoute
  '/ownership': typeof OwnershipRoute
  '/pages': typeof PagesRoute
  '/plans': typeof PlansRoute
  '/security': typeof SecurityRoute
  '/ai_/automation': typeof AiAutomationRoute
  '/ai_/credits': typeof AiCreditsRoute
  '/ai_/knowledge': typeof AiKnowledgeRoute
  '/ai_/studio': typeof AiStudioRoute
  '/app/account': typeof AppAccountRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/founder': typeof AppFounderRoute
  '/app/org': typeof AppOrgRouteWithChildren
  '/app/people': typeof AppPeopleRoute
  '/app/search': typeof AppSearchRoute
  '/app/work': typeof AppWorkRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/addresses': typeof AppAdminAddressesRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/export': typeof AppAdminExportRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/teams': typeof AppAdminTeamsRoute
  '/app/crm/activity': typeof AppCrmActivityRoute
  '/app/crm/collab': typeof AppCrmCollabRoute
  '/app/crm/leads': typeof AppCrmLeadsRoute
  '/app/crm/pipeline': typeof AppCrmPipelineRoute
  '/app/founder_/ai': typeof AppFounderAiRouteWithChildren
  '/app/founder_/crm': typeof AppFounderCrmRoute
  '/app/founder_/org': typeof AppFounderOrgRoute
  '/app/mail/$folder': typeof AppMailFolderRouteWithChildren
  '/app/org/audit': typeof AppOrgAuditRoute
  '/app/org/compliance': typeof AppOrgComplianceRoute
  '/app/org/departments': typeof AppOrgDepartmentsRoute
  '/app/org/graph': typeof AppOrgGraphRoute
  '/app/org/members': typeof AppOrgMembersRoute
  '/app/org/policies': typeof AppOrgPoliciesRoute
  '/app/org/roles': typeof AppOrgRolesRoute
  '/app/org/security': typeof AppOrgSecurityRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/org/': typeof AppOrgIndexRoute
  '/app/founder_/ai/arena': typeof AppFounderAiArenaRoute
  '/app/founder_/ai/automation': typeof AppFounderAiAutomationRoute
  '/app/founder_/ai/billing': typeof AppFounderAiBillingRoute
  '/app/founder_/ai/memory': typeof AppFounderAiMemoryRoute
  '/app/founder_/ai/prompts': typeof AppFounderAiPromptsRoute
  '/app/founder_/ai/receipts': typeof AppFounderAiReceiptsRoute
  '/app/founder_/ai/studio': typeof AppFounderAiStudioRoute
  '/app/mail/$folder/$threadId': typeof AppMailFolderThreadIdRoute
  '/app/founder_/ai/': typeof AppFounderAiIndexRoute
  '/app/mail/$folder/': typeof AppMailFolderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/app'
    | '/auth'
    | '/claim'
    | '/move-in'
    | '/onboarding'
    | '/ownership'
    | '/pages'
    | '/plans'
    | '/security'
    | '/ai/automation'
    | '/ai/credits'
    | '/ai/knowledge'
    | '/ai/studio'
    | '/app/account'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/calendar'
    | '/app/crm'
    | '/app/founder'
    | '/app/org'
    | '/app/people'
    | '/app/search'
    | '/app/work'
    | '/auth/callback'
    | '/app/'
    | '/app/admin/addresses'
    | '/app/admin/audit'
    | '/app/admin/export'
    | '/app/admin/members'
    | '/app/admin/teams'
    | '/app/crm/activity'
    | '/app/crm/collab'
    | '/app/crm/leads'
    | '/app/crm/pipeline'
    | '/app/founder/ai'
    | '/app/founder/crm'
    | '/app/founder/org'
    | '/app/mail/$folder'
    | '/app/org/audit'
    | '/app/org/compliance'
    | '/app/org/departments'
    | '/app/org/graph'
    | '/app/org/members'
    | '/app/org/policies'
    | '/app/org/roles'
    | '/app/org/security'
    | '/app/admin/'
    | '/app/crm/'
    | '/app/org/'
    | '/app/founder/ai/arena'
    | '/app/founder/ai/automation'
    | '/app/founder/ai/billing'
    | '/app/founder/ai/memory'
    | '/app/founder/ai/prompts'
    | '/app/founder/ai/receipts'
    | '/app/founder/ai/studio'
    | '/app/mail/$folder/$threadId'
    | '/app/founder/ai/'
    | '/app/mail/$folder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/claim'
    | '/move-in'
    | '/onboarding'
    | '/ownership'
    | '/pages'
    | '/plans'
    | '/security'
    | '/ai/automation'
    | '/ai/credits'
    | '/ai/knowledge'
    | '/ai/studio'
    | '/app/account'
    | '/app/ai-center'
    | '/app/calendar'
    | '/app/founder'
    | '/app/people'
    | '/app/search'
    | '/app/work'
    | '/auth/callback'
    | '/app'
    | '/app/admin/addresses'
    | '/app/admin/audit'
    | '/app/admin/export'
    | '/app/admin/members'
    | '/app/admin/teams'
    | '/app/crm/activity'
    | '/app/crm/collab'
    | '/app/crm/leads'
    | '/app/crm/pipeline'
    | '/app/founder/crm'
    | '/app/founder/org'
    | '/app/org/audit'
    | '/app/org/compliance'
    | '/app/org/departments'
    | '/app/org/graph'
    | '/app/org/members'
    | '/app/org/policies'
    | '/app/org/roles'
    | '/app/org/security'
    | '/app/admin'
    | '/app/crm'
    | '/app/org'
    | '/app/founder/ai/arena'
    | '/app/founder/ai/automation'
    | '/app/founder/ai/billing'
    | '/app/founder/ai/memory'
    | '/app/founder/ai/prompts'
    | '/app/founder/ai/receipts'
    | '/app/founder/ai/studio'
    | '/app/mail/$folder/$threadId'
    | '/app/founder/ai'
    | '/app/mail/$folder'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/app'
    | '/auth'
    | '/claim'
    | '/move-in'
    | '/onboarding'
    | '/ownership'
    | '/pages'
    | '/plans'
    | '/security'
    | '/ai_/automation'
    | '/ai_/credits'
    | '/ai_/knowledge'
    | '/ai_/studio'
    | '/app/account'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/calendar'
    | '/app/crm'
    | '/app/founder'
    | '/app/org'
    | '/app/people'
    | '/app/search'
    | '/app/work'
    | '/auth_/callback'
    | '/app/'
    | '/app/admin/addresses'
    | '/app/admin/audit'
    | '/app/admin/export'
    | '/app/admin/members'
    | '/app/admin/teams'
    | '/app/crm/activity'
    | '/app/crm/collab'
    | '/app/crm/leads'
    | '/app/crm/pipeline'
    | '/app/founder_/ai'
    | '/app/founder_/crm'
    | '/app/founder_/org'
    | '/app/mail/$folder'
    | '/app/org/audit'
    | '/app/org/compliance'
    | '/app/org/departments'
    | '/app/org/graph'
    | '/app/org/members'
    | '/app/org/policies'
    | '/app/org/roles'
    | '/app/org/security'
    | '/app/admin/'
    | '/app/crm/'
    | '/app/org/'
    | '/app/founder_/ai/arena'
    | '/app/founder_/ai/automation'
    | '/app/founder_/ai/billing'
    | '/app/founder_/ai/memory'
    | '/app/founder_/ai/prompts'
    | '/app/founder_/ai/receipts'
    | '/app/founder_/ai/studio'
    | '/app/mail/$folder/$threadId'
    | '/app/founder_/ai/'
    | '/app/mail/$folder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClaimRoute: typeof ClaimRoute
  MoveInRoute: typeof MoveInRoute
  OnboardingRoute: typeof OnboardingRoute
  OwnershipRoute: typeof OwnershipRoute
  PagesRoute: typeof PagesRoute
  PlansRoute: typeof PlansRoute
  SecurityRoute: typeof SecurityRoute
  AiAutomationRoute: typeof AiAutomationRoute
  AiCreditsRoute: typeof AiCreditsRoute
  AiKnowledgeRoute: typeof AiKnowledgeRoute
  AiStudioRoute: typeof AiStudioRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move-in': {
      id: '/move-in'
      path: '/move-in'
      fullPath: '/move-in'
      preLoaderRoute: typeof MoveInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ownership': {
      id: '/ownership'
      path: '/ownership'
      fullPath: '/ownership'
      preLoaderRoute: typeof OwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai_/automation': {
      id: '/ai_/automation'
      path: '/ai/automation'
      fullPath: '/ai/automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai_/credits': {
      id: '/ai_/credits'
      path: '/ai/credits'
      fullPath: '/ai/credits'
      preLoaderRoute: typeof AiCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai_/knowledge': {
      id: '/ai_/knowledge'
      path: '/ai/knowledge'
      fullPath: '/ai/knowledge'
      preLoaderRoute: typeof AiKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai_/studio': {
      id: '/ai_/studio'
      path: '/ai/studio'
      fullPath: '/ai/studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-center': {
      id: '/app/ai-center'
      path: '/ai-center'
      fullPath: '/app/ai-center'
      preLoaderRoute: typeof AppAiCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/founder': {
      id: '/app/founder'
      path: '/founder'
      fullPath: '/app/founder'
      preLoaderRoute: typeof AppFounderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org': {
      id: '/app/org'
      path: '/org'
      fullPath: '/app/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/work': {
      id: '/app/work'
      path: '/work'
      fullPath: '/app/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/addresses': {
      id: '/app/admin/addresses'
      path: '/addresses'
      fullPath: '/app/admin/addresses'
      preLoaderRoute: typeof AppAdminAddressesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/export': {
      id: '/app/admin/export'
      path: '/export'
      fullPath: '/app/admin/export'
      preLoaderRoute: typeof AppAdminExportRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/members': {
      id: '/app/admin/members'
      path: '/members'
      fullPath: '/app/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/teams': {
      id: '/app/admin/teams'
      path: '/teams'
      fullPath: '/app/admin/teams'
      preLoaderRoute: typeof AppAdminTeamsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/crm/': {
      id: '/app/crm/'
      path: '/'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/activity': {
      id: '/app/crm/activity'
      path: '/activity'
      fullPath: '/app/crm/activity'
      preLoaderRoute: typeof AppCrmActivityRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/collab': {
      id: '/app/crm/collab'
      path: '/collab'
      fullPath: '/app/crm/collab'
      preLoaderRoute: typeof AppCrmCollabRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/leads': {
      id: '/app/crm/leads'
      path: '/leads'
      fullPath: '/app/crm/leads'
      preLoaderRoute: typeof AppCrmLeadsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/pipeline': {
      id: '/app/crm/pipeline'
      path: '/pipeline'
      fullPath: '/app/crm/pipeline'
      preLoaderRoute: typeof AppCrmPipelineRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/founder_/ai': {
      id: '/app/founder_/ai'
      path: '/founder/ai'
      fullPath: '/app/founder/ai'
      preLoaderRoute: typeof AppFounderAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/founder_/crm': {
      id: '/app/founder_/crm'
      path: '/founder/crm'
      fullPath: '/app/founder/crm'
      preLoaderRoute: typeof AppFounderCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/founder_/org': {
      id: '/app/founder_/org'
      path: '/founder/org'
      fullPath: '/app/founder/org'
      preLoaderRoute: typeof AppFounderOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mail/$folder': {
      id: '/app/mail/$folder'
      path: '/mail/$folder'
      fullPath: '/app/mail/$folder'
      preLoaderRoute: typeof AppMailFolderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/': {
      id: '/app/org/'
      path: '/'
      fullPath: '/app/org/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/org/audit': {
      id: '/app/org/audit'
      path: '/audit'
      fullPath: '/app/org/audit'
      preLoaderRoute: typeof AppOrgAuditRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/org/compliance': {
      id: '/app/org/compliance'
      path: '/compliance'
      fullPath: '/app/org/compliance'
      preLoaderRoute: typeof AppOrgComplianceRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/org/departments': {
      id: '/app/org/departments'
      path: '/departments'
      fullPath: '/app/org/departments'
      preLoaderRoute: typeof AppOrgDepartmentsRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/org/graph': {
      id: '/app/org/graph'
      path: '/graph'
      fullPath: '/app/org/graph'
      preLoaderRoute: typeof AppOrgGraphRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/org/members': {
      id: '/app/org/members'
      path: '/members'
      fullPath: '/app/org/members'
      preLoaderRoute: typeof AppOrgMembersRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/org/policies': {
      id: '/app/org/policies'
      path: '/policies'
      fullPath: '/app/org/policies'
      preLoaderRoute: typeof AppOrgPoliciesRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/org/roles': {
      id: '/app/org/roles'
      path: '/roles'
      fullPath: '/app/org/roles'
      preLoaderRoute: typeof AppOrgRolesRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/org/security': {
      id: '/app/org/security'
      path: '/security'
      fullPath: '/app/org/security'
      preLoaderRoute: typeof AppOrgSecurityRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/founder_/ai/': {
      id: '/app/founder_/ai/'
      path: '/'
      fullPath: '/app/founder/ai/'
      preLoaderRoute: typeof AppFounderAiIndexRouteImport
      parentRoute: typeof AppFounderAiRoute
    }
    '/app/founder_/ai/arena': {
      id: '/app/founder_/ai/arena'
      path: '/arena'
      fullPath: '/app/founder/ai/arena'
      preLoaderRoute: typeof AppFounderAiArenaRouteImport
      parentRoute: typeof AppFounderAiRoute
    }
    '/app/founder_/ai/automation': {
      id: '/app/founder_/ai/automation'
      path: '/automation'
      fullPath: '/app/founder/ai/automation'
      preLoaderRoute: typeof AppFounderAiAutomationRouteImport
      parentRoute: typeof AppFounderAiRoute
    }
    '/app/founder_/ai/billing': {
      id: '/app/founder_/ai/billing'
      path: '/billing'
      fullPath: '/app/founder/ai/billing'
      preLoaderRoute: typeof AppFounderAiBillingRouteImport
      parentRoute: typeof AppFounderAiRoute
    }
    '/app/founder_/ai/memory': {
      id: '/app/founder_/ai/memory'
      path: '/memory'
      fullPath: '/app/founder/ai/memory'
      preLoaderRoute: typeof AppFounderAiMemoryRouteImport
      parentRoute: typeof AppFounderAiRoute
    }
    '/app/founder_/ai/prompts': {
      id: '/app/founder_/ai/prompts'
      path: '/prompts'
      fullPath: '/app/founder/ai/prompts'
      preLoaderRoute: typeof AppFounderAiPromptsRouteImport
      parentRoute: typeof AppFounderAiRoute
    }
    '/app/founder_/ai/receipts': {
      id: '/app/founder_/ai/receipts'
      path: '/receipts'
      fullPath: '/app/founder/ai/receipts'
      preLoaderRoute: typeof AppFounderAiReceiptsRouteImport
      parentRoute: typeof AppFounderAiRoute
    }
    '/app/founder_/ai/studio': {
      id: '/app/founder_/ai/studio'
      path: '/studio'
      fullPath: '/app/founder/ai/studio'
      preLoaderRoute: typeof AppFounderAiStudioRouteImport
      parentRoute: typeof AppFounderAiRoute
    }
    '/app/mail/$folder/': {
      id: '/app/mail/$folder/'
      path: '/'
      fullPath: '/app/mail/$folder/'
      preLoaderRoute: typeof AppMailFolderIndexRouteImport
      parentRoute: typeof AppMailFolderRoute
    }
    '/app/mail/$folder/$threadId': {
      id: '/app/mail/$folder/$threadId'
      path: '/$threadId'
      fullPath: '/app/mail/$folder/$threadId'
      preLoaderRoute: typeof AppMailFolderThreadIdRouteImport
      parentRoute: typeof AppMailFolderRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAddressesRoute: typeof AppAdminAddressesRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminExportRoute: typeof AppAdminExportRoute
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppAdminTeamsRoute: typeof AppAdminTeamsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAddressesRoute: AppAdminAddressesRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminExportRoute: AppAdminExportRoute,
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppAdminTeamsRoute: AppAdminTeamsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppCrmRouteChildren {
  AppCrmActivityRoute: typeof AppCrmActivityRoute
  AppCrmCollabRoute: typeof AppCrmCollabRoute
  AppCrmLeadsRoute: typeof AppCrmLeadsRoute
  AppCrmPipelineRoute: typeof AppCrmPipelineRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmActivityRoute: AppCrmActivityRoute,
  AppCrmCollabRoute: AppCrmCollabRoute,
  AppCrmLeadsRoute: AppCrmLeadsRoute,
  AppCrmPipelineRoute: AppCrmPipelineRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppOrgRouteChildren {
  AppOrgAuditRoute: typeof AppOrgAuditRoute
  AppOrgComplianceRoute: typeof AppOrgComplianceRoute
  AppOrgDepartmentsRoute: typeof AppOrgDepartmentsRoute
  AppOrgGraphRoute: typeof AppOrgGraphRoute
  AppOrgMembersRoute: typeof AppOrgMembersRoute
  AppOrgPoliciesRoute: typeof AppOrgPoliciesRoute
  AppOrgRolesRoute: typeof AppOrgRolesRoute
  AppOrgSecurityRoute: typeof AppOrgSecurityRoute
  AppOrgIndexRoute: typeof AppOrgIndexRoute
}

const AppOrgRouteChildren: AppOrgRouteChildren = {
  AppOrgAuditRoute: AppOrgAuditRoute,
  AppOrgComplianceRoute: AppOrgComplianceRoute,
  AppOrgDepartmentsRoute: AppOrgDepartmentsRoute,
  AppOrgGraphRoute: AppOrgGraphRoute,
  AppOrgMembersRoute: AppOrgMembersRoute,
  AppOrgPoliciesRoute: AppOrgPoliciesRoute,
  AppOrgRolesRoute: AppOrgRolesRoute,
  AppOrgSecurityRoute: AppOrgSecurityRoute,
  AppOrgIndexRoute: AppOrgIndexRoute,
}

const AppOrgRouteWithChildren =
  AppOrgRoute._addFileChildren(AppOrgRouteChildren)

interface AppFounderAiRouteChildren {
  AppFounderAiArenaRoute: typeof AppFounderAiArenaRoute
  AppFounderAiAutomationRoute: typeof AppFounderAiAutomationRoute
  AppFounderAiBillingRoute: typeof AppFounderAiBillingRoute
  AppFounderAiMemoryRoute: typeof AppFounderAiMemoryRoute
  AppFounderAiPromptsRoute: typeof AppFounderAiPromptsRoute
  AppFounderAiReceiptsRoute: typeof AppFounderAiReceiptsRoute
  AppFounderAiStudioRoute: typeof AppFounderAiStudioRoute
  AppFounderAiIndexRoute: typeof AppFounderAiIndexRoute
}

const AppFounderAiRouteChildren: AppFounderAiRouteChildren = {
  AppFounderAiArenaRoute: AppFounderAiArenaRoute,
  AppFounderAiAutomationRoute: AppFounderAiAutomationRoute,
  AppFounderAiBillingRoute: AppFounderAiBillingRoute,
  AppFounderAiMemoryRoute: AppFounderAiMemoryRoute,
  AppFounderAiPromptsRoute: AppFounderAiPromptsRoute,
  AppFounderAiReceiptsRoute: AppFounderAiReceiptsRoute,
  AppFounderAiStudioRoute: AppFounderAiStudioRoute,
  AppFounderAiIndexRoute: AppFounderAiIndexRoute,
}

const AppFounderAiRouteWithChildren = AppFounderAiRoute._addFileChildren(
  AppFounderAiRouteChildren,
)

interface AppMailFolderRouteChildren {
  AppMailFolderThreadIdRoute: typeof AppMailFolderThreadIdRoute
  AppMailFolderIndexRoute: typeof AppMailFolderIndexRoute
}

const AppMailFolderRouteChildren: AppMailFolderRouteChildren = {
  AppMailFolderThreadIdRoute: AppMailFolderThreadIdRoute,
  AppMailFolderIndexRoute: AppMailFolderIndexRoute,
}

const AppMailFolderRouteWithChildren = AppMailFolderRoute._addFileChildren(
  AppMailFolderRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAiCenterRoute: typeof AppAiCenterRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppFounderRoute: typeof AppFounderRoute
  AppOrgRoute: typeof AppOrgRouteWithChildren
  AppPeopleRoute: typeof AppPeopleRoute
  AppSearchRoute: typeof AppSearchRoute
  AppWorkRoute: typeof AppWorkRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFounderAiRoute: typeof AppFounderAiRouteWithChildren
  AppFounderCrmRoute: typeof AppFounderCrmRoute
  AppFounderOrgRoute: typeof AppFounderOrgRoute
  AppMailFolderRoute: typeof AppMailFolderRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAiCenterRoute: AppAiCenterRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCrmRoute: AppCrmRouteWithChildren,
  AppFounderRoute: AppFounderRoute,
  AppOrgRoute: AppOrgRouteWithChildren,
  AppPeopleRoute: AppPeopleRoute,
  AppSearchRoute: AppSearchRoute,
  AppWorkRoute: AppWorkRoute,
  AppIndexRoute: AppIndexRoute,
  AppFounderAiRoute: AppFounderAiRouteWithChildren,
  AppFounderCrmRoute: AppFounderCrmRoute,
  AppFounderOrgRoute: AppFounderOrgRoute,
  AppMailFolderRoute: AppMailFolderRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ClaimRoute: ClaimRoute,
  MoveInRoute: MoveInRoute,
  OnboardingRoute: OnboardingRoute,
  OwnershipRoute: OwnershipRoute,
  PagesRoute: PagesRoute,
  PlansRoute: PlansRoute,
  SecurityRoute: SecurityRoute,
  AiAutomationRoute: AiAutomationRoute,
  AiCreditsRoute: AiCreditsRoute,
  AiKnowledgeRoute: AiKnowledgeRoute,
  AiStudioRoute: AiStudioRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
